name: Meu Primeiro Robô de CI

# GATILHO (Quando esse robô deve acordar?)
on:
  push:
    branches:
      - master

# O QUE ELE VAI FAZER?
jobs:
  meu_primeiro_job:
  # ONDE ELE VAI TRABALHAR? (O Runner)
    runs-on: ubuntu-latest

# PASSO A PASSO

    steps:
      - name: Dizer Ola
        run: echo "Ola, Faculdade! Meu primeiro CI rodou com sucesso."

      - name: Mostrar informações da máquina
        run: uname -a